site_name: RDK Architecture
edit_uri: "https://ranjeetha-documentation.github.io/docs-ver/"

plugins:
- mkdocs-versioning:
    version: 0.3.0
nav:
  - Home: "index.md"
  - Version Selector: "../"
  # - awesome-pages